# Generated by Django 4.2.6 on 2024-12-20 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_rename_seller_seller_name_alter_seller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Descripcion')),
                ('trademark', models.CharField(max_length=20, verbose_name='Marca')),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=7, verbose_name='Contenido')),
                ('unit', models.CharField(choices=[('Lt', 'Litro'), ('Kg', 'Kilogramo'), ('Pza', 'Pieza'), ('Caja', 'Caja'), ('Paquete', 'Paquete'), ('Rollos', 'Rollos')], max_length=7, verbose_name='Unidad')),
                ('package', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Paquete')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ean', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999999999)], verbose_name='Paquete')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
    ]
