# Generated by Django 4.2.6 on 2024-12-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_article_alter_seller_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='trademark',
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Descripcion'),
        ),
    ]
