# Generated by Django 4.2.6 on 2024-12-28 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_remove_article_trademark_alter_article_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ean',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999999)], verbose_name='EAN'),
        ),
        migrations.AlterField(
            model_name='article',
            name='package',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Paquete'),
        ),
    ]
