# Generated by Django 4.2.6 on 2025-01-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_alter_article_ean_alter_article_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Descripcion'),
        ),
    ]
