# Generated by Django 4.2.6 on 2025-01-10 20:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_alter_article_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio U')),
                ('note', models.CharField(max_length=25, verbose_name='Comentario')),
                ('article', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='shopapp.article')),
                ('seller', models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='shopapp.seller')),
            ],
        ),
    ]
