# Generated by Django 4.2.6 on 2025-02-23 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_division_family_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='Division',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='shopapp.division'),
        ),
    ]
