# Generated by Django 4.2.6 on 2025-02-23 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_family_division'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'Division', 'verbose_name_plural': 'Divisions'},
        ),
        migrations.RenameField(
            model_name='family',
            old_name='Division',
            new_name='division',
        ),
        migrations.AddField(
            model_name='article',
            name='family',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='shopapp.family'),
        ),
    ]
